# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
workflows:
  version: 2
  main:
    jobs:
      - build_hcs_lib:
        filters: # required since `release_artifacts` has tag filters AND requires `this`
            branches:
              only: /.*/
            tags:
              only: /.*/
      # - build_hcs_relay:
      #     filters: # required since `release_artifacts` has tag filters AND requires `this`
      #       branches:
      #         only: /.*/
      #       tags:
      #         only: /.*/
      # - build_hcs_example:
      #     filters: # required since `release_artifacts` has tag filters AND requires `this`
      #       branches:
      #         only: /.*/
      #       tags:
      #         only: /.*/
  jobs:
    build_hcs_lib:
      docker:
        - image: adoptopenjdk:10-jdk-hotspot
          environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

      steps:
        - checkout
        - restore_cache:
            keys:
              - maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
              - maven-v1-{{ .Branch }}
              - maven-v1-
        - run:
            name: Running maven (validate, compile, test, package)
            command: cd hcs-lib; ./mvnw package
        - save_cache:
            key: maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
            - ~/.m2
        - store_test_results:
            path: target/surefire-reports

    build_hcs_relay:
      docker:
        - image: adoptopenjdk:10-jdk-hotspot
          environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

      steps:
        - checkout
        - restore_cache:
            keys:
              - maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
              - maven-v1-{{ .Branch }}
              - maven-v1-
        - run:
            name: Running maven (validate, compile, test, package)
            command: cd hcs-lib; ./mvnw package
        - save_cache:
            key: maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
            - ~/.m2
        - store_test_results:
            path: target/surefire-reports

    build_hcs_example:
      docker:
        - image: adoptopenjdk:10-jdk-hotspot
          environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

      steps:
        - checkout
        - restore_cache:
            keys:
              - maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
              - maven-v1-{{ .Branch }}
              - maven-v1-
        - run:
            name: Running maven (validate, compile, test, package)
            command: cd examples/simple-message-demo; ./mvnw package
        - save_cache:
            key: maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
            - ~/.m2
        - store_test_results:
            path: target/surefire-reports
