# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build
    working_directory: ~/hcs-lib
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:10-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Trigger Builds
          command:
            trigger_job build-hcs-lib
            trigger_job build-hcs-relay
            trigger_job build-hcs-simple-message-demo
  build-hcs-lib:
    working_directory: ~/hcs-lib
    steps:
      - run: cd hcs-lib; ./mvnw package
  build-hcs-relay:
    working_directory: ~/hcs-lib
    steps:
      - run: cd hcs-relay; ./mvnw package
  build-hcs-simple-message-demo:
    working_directory: ~/hcs-lib
    steps:
      - run: cd examples/simple-message-demo; ./mvnw package
