# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
workflows:
  version: 2
  main:
    jobs:
      - build_hcs_sdk
      # - build_hcs_lib
jobs:
  build_hcs_sdk:
    docker:
      - image: maven:latest #adoptopenjdk:11-jdk-hotspot
        environment:
          # Customize the JVM maximum heap limit
          MAVEN_OPTS: -Xmx3200m

    steps:
      - run:
          name: Running git pull on hcs java sdk
          command: git pull origin HCS git@github.com:mike-burrage-hedera/hedera-sdk-java.git
      - run:
          name: compiling hcs java sdk
          command: cd hedera-sdk-java
      - run:
          name: Running maven (install - skipping tests)
          command: ./mvn install -DskipTests
  build_hcs_lib:
    docker:
      - image: adoptopenjdk:11-jdk-hotspot
        environment:
          # Customize the JVM maximum heap limit
          MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-v1-{{ .Branch }}
            - maven-v1-
      - run:
          name: Running maven (validate, compile, test, package)
          command: ./mvnw package
      - save_cache:
          key: maven-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - store_test_results:
          path: target/surefire-reports
