version: '3.3'
services:
  hcsqueue:
    image: vromero/activemq-artemis:2.10.1-alpine
    restart: on-failure
    ports:
      # ui
      - "8161:8161"
      # jms
      - "61616:61616"
    networks: [backing-services]
    volumes: [
      "activemq-data:/var/lib/artemis/data"
      , "activemq-data:/var/lib/artemis/etc"
      , "activemq-data:/var/lib/artemis/etc-override"
      , "activemq-data:/var/lib/artemis/lock"
      , "activemq-data:/opt/jmx-exporter/etc-override"
    ]
    
    environment: [
      ARTEMIS_USERNAME=hcsdemo
      ,ARTEMIS_PASSWORD=hcsdemo
      ,RESTORE_CONFIGURATION=true
    ]
    
  hcs-relay:
    image: hederahashgraph/hcs-relay
    restart: on-failure
    networks: [backing-services]

  # this runs the apps
  # player1:
  #  image: hederahashgraph/hcs-app
  #  restart: always
  #  environment:
  #    - APPID=0
  #  tty: true
  #  ports:
  #    - 8080:8080
 
  # player2:
  #   image:
  #   restart: always
  #   environment:
  #     - APPID=1
  #   tty: true
  #   ports:
  #     - 8080:8081

volumes:
  activemq-data: {}

networks:
  backing-services:
    driver: bridge
